# Generated by Django 4.2.4 on 2023-08-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(related_name='programs', to='programs.program'),
        ),
    ]
