# Generated by Django 4.2.4 on 2023-08-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
